preload = ~/wallpapers/m1.png
preload = ~/wallpapers/m2.png
preload = ~/wallpapers/m3.png
preload = ~/wallpapers/m4.png
preload = ~/wallpapers/lock.png

wallpaper = DP-2,~/wallpapers/m1.png
wallpaper = DP-4,~/wallpapers/m2.png
wallpaper = HDMI-A-2,~/wallpapers/m3.png
wallpaper = DP-3,~/wallpapers/m4.png
splash = false
ipc = off
