preload = ~/wallpapers/0.png
wallpaper = DP-2,~/wallpapers/0.png
wallpaper = DP-4,~/wallpapers/0.png
wallpaper = DP-3,~/wallpapers/0.png
wallpaper = HDMI-A-2,~/wallpapers/0.png
splash = false
ipc = off
